import { useParams, useNavigate, Link, Navigate } from 'react-router-dom'
import { useState, useEffect, useMemo } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  ArrowLeft,
  ArrowRight,
  ExternalLink,
  Calendar,
  User,
  Clock,
  Target,
  Compass,
  Trophy,
  Copy,
  Check,
  Search,
  Sparkles,
  Maximize2,
  X,
  ChevronLeft,
  ChevronRight,
  RefreshCw,
  Zap,
  Lock,
  Share2,
  CheckCircle2,
  FileCode,
  AlertTriangle,
  ShieldAlert,
} from 'lucide-react'
import { FiGithub } from 'react-icons/fi'
import { SEO } from '../components/SEO'
import { portfolioData } from '../data/portfolioData'
import { TechBadge } from '../components/ui/TechBadge'
import { SpotlightCard } from '../components/ui/SpotlightCard'
import { SectionDivider } from '../components/ui/SectionDivider'
import { APPLE_EASE, cn } from '../lib/utils'

const { projects } = portfolioData

/* ────────────────────────────────────────────────────────────────────────── */
/* 1. INTERACTIVE SIMULATORS FOR EACH PROJECT                                */
/* ────────────────────────────────────────────────────────────────────────── */

/** MigrationMap Interactive Sandbox: Live Redirect Config Generator */
function MigrationMapSimulator() {
  const [sourceUrl, setSourceUrl] = useState('/blog/old-react-tutorial')
  const [targetUrl, setTargetUrl] = useState('/articles/react-patterns')
  const [statusCode, setStatusCode] = useState<'301' | '308' | '302'>('301')
  const [configFormat, setConfigFormat] = useState<'nextjs' | 'vercel' | 'netlify' | 'nginx' | 'apache'>('nextjs')
  const [copied, setCopied] = useState(false)

  const isSelfRedirect = sourceUrl.trim().toLowerCase() === targetUrl.trim().toLowerCase()

  const generatedCode = useMemo(() => {
    const isPermanent = statusCode === '301' || statusCode === '308'
    switch (configFormat) {
      case 'nextjs':
        return `// next.config.js - Generated by MigrationMap\nmodule.exports = {\n  async redirects() {\n    return [\n      {\n        source: '${sourceUrl}',\n        destination: '${targetUrl}',\n        permanent: ${isPermanent},\n      },\n    ]\n  },\n}`
      case 'vercel':
        return `// vercel.json - Generated by MigrationMap\n{\n  "redirects": [\n    {\n      "source": "${sourceUrl}",\n      "destination": "${targetUrl}",\n      "permanent": ${isPermanent}\n    }\n  ]\n}`
      case 'netlify':
        return `# _redirects - Generated by MigrationMap\n${sourceUrl}  ${targetUrl}  ${statusCode}!`
      case 'nginx':
        return `# nginx.conf - Generated by MigrationMap\nlocation = ${sourceUrl} {\n    return ${statusCode} ${targetUrl};\n}`
      case 'apache':
        return `# .htaccess - Generated by MigrationMap\nRedirect ${statusCode} ${sourceUrl} ${targetUrl}`
    }
  }, [sourceUrl, targetUrl, statusCode, configFormat])

  const copyConfig = () => {
    navigator.clipboard.writeText(generatedCode)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="rounded-2xl border border-blue-500/20 bg-[#07101f] p-6 sm:p-8 lg:p-9 shadow-2xl">
      <div className="flex flex-wrap items-center justify-between gap-4 pb-6 border-b border-white/[0.08]">
        <div>
          <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-md bg-blue-500/10 border border-blue-500/25 mb-2">
            <Sparkles className="size-3 text-blue-400" />
            <span className="font-mono text-[10px] font-bold uppercase tracking-wider text-blue-300">Live Simulator</span>
          </div>
          <h3 className="font-heading font-bold text-white text-base sm:text-lg">
            Instant Redirect Engine &amp; Config Exporter
          </h3>
          <p className="text-zinc-400 text-xs sm:text-sm mt-1">
            Test MigrationMap's mapping logic and generate deployment-ready rules in real time.
          </p>
        </div>

        <div className="flex items-center gap-2">
          {isSelfRedirect ? (
            <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-rose-500/10 border border-rose-500/30 text-rose-400 text-xs font-mono">
              <AlertTriangle className="size-3.5" /> Self-Redirect Detected
            </span>
          ) : (
            <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-mono">
              <CheckCircle2 className="size-3.5" /> Mapping Validated
            </span>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 my-6 sm:my-8">
        <div>
          <label className="block text-[11px] font-mono text-zinc-400 uppercase tracking-wider mb-2">
            Legacy Source URL
          </label>
          <input
            type="text"
            value={sourceUrl}
            onChange={(e) => setSourceUrl(e.target.value)}
            className="w-full px-4 py-3 rounded-xl bg-white/[0.04] border border-white/[0.1] text-xs sm:text-sm text-white font-mono focus:outline-none focus:border-blue-500/50"
            placeholder="/old-url"
          />
        </div>

        <div>
          <label className="block text-[11px] font-mono text-zinc-400 uppercase tracking-wider mb-2">
            Target Destination URL
          </label>
          <input
            type="text"
            value={targetUrl}
            onChange={(e) => setTargetUrl(e.target.value)}
            className="w-full px-4 py-3 rounded-xl bg-white/[0.04] border border-white/[0.1] text-xs sm:text-sm text-white font-mono focus:outline-none focus:border-blue-500/50"
            placeholder="/new-url"
          />
        </div>
      </div>

      <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
        <div className="flex flex-wrap items-center gap-2.5">
          <span className="text-xs text-zinc-400 font-mono">Status:</span>
          {(['301', '308', '302'] as const).map((code) => (
            <button
              key={code}
              onClick={() => setStatusCode(code)}
              className={cn(
                'px-2.5 py-1 rounded-md text-xs font-mono transition-all',
                statusCode === code
                  ? 'bg-blue-500/20 text-blue-300 border border-blue-500/40'
                  : 'bg-white/[0.03] text-zinc-400 border border-white/[0.06] hover:text-white',
              )}
            >
              HTTP {code}
            </button>
          ))}
        </div>

        <div className="flex flex-wrap items-center gap-1.5">
          <span className="text-xs text-zinc-400 font-mono">Export:</span>
          {(['nextjs', 'vercel', 'netlify', 'nginx', 'apache'] as const).map((fmt) => (
            <button
              key={fmt}
              onClick={() => setConfigFormat(fmt)}
              className={cn(
                'px-2.5 py-1 rounded-md text-xs font-mono capitalize transition-all',
                configFormat === fmt
                  ? 'bg-blue-500/20 text-blue-300 border border-blue-500/40'
                  : 'bg-white/[0.03] text-zinc-400 border border-white/[0.06] hover:text-white',
              )}
            >
              {fmt === 'nextjs' ? 'Next.js' : fmt}
            </button>
          ))}
        </div>
      </div>

      <div className="relative rounded-xl border border-white/[0.08] bg-black/60 p-4 font-mono text-xs text-blue-200 overflow-x-auto">
        <button
          onClick={copyConfig}
          className="absolute top-3 right-3 flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-white text-xs font-mono transition-all"
        >
          {copied ? <Check className="size-3.5 text-emerald-400" /> : <Copy className="size-3.5" />}
          <span>{copied ? 'Copied!' : 'Copy Config'}</span>
        </button>
        <pre className="pr-24">{generatedCode}</pre>
      </div>
    </div>
  )
}

/** HookScope Interactive Sandbox: Live Webhook Payload & Replay Inspector */
function HookScopeSimulator() {
  const [selectedEvent, setSelectedEvent] = useState<'stripe' | 'github' | 'shopify'>('stripe')
  const [isReplaying, setIsReplaying] = useState(false)
  const [replaySuccess, setReplaySuccess] = useState(false)
  const [copied, setCopied] = useState(false)

  const events = {
    stripe: {
      type: 'payment_intent.succeeded',
      headers: {
        'content-type': 'application/json',
        'stripe-signature': 't=1728345600,v1=9c4a854d92eb962f3a9a83...',
        'user-agent': 'Stripe/1.0 (+https://stripe.com/docs/webhooks)',
      },
      payload: {
        id: 'pi_3MtwBwLkdIwHu7ix28a3tqPa',
        object: 'payment_intent',
        amount: 8900,
        currency: 'usd',
        status: 'succeeded',
        customer: 'cus_N8yV1A90xyz',
      },
    },
    github: {
      type: 'push',
      headers: {
        'content-type': 'application/json',
        'x-github-event': 'push',
        'x-hub-signature-256': 'sha256=4f27e56214300a7b4515...',
        'user-agent': 'GitHub-Hookshot/7b8c9d1',
      },
      payload: {
        ref: 'refs/heads/main',
        repository: { name: 'hookscope-tools', default_branch: 'main' },
        pusher: { name: 'usmankhtri' },
        commits: [{ message: 'feat: add hmac signature verification engine' }],
      },
    },
    shopify: {
      type: 'orders/create',
      headers: {
        'content-type': 'application/json',
        'x-shopify-topic': 'orders/create',
        'x-shopify-hmac-sha256': 'WVN5K9oP3Y...=',
        'x-shopify-shop-domain': 'store.myshopify.com',
      },
      payload: {
        id: 549823901239,
        total_price: '149.50',
        currency: 'USD',
        financial_status: 'paid',
        line_items_count: 2,
      },
    },
  }

  const current = events[selectedEvent]

  const handleReplay = () => {
    setIsReplaying(true)
    setReplaySuccess(false)
    setTimeout(() => {
      setIsReplaying(false)
      setReplaySuccess(true)
      setTimeout(() => setReplaySuccess(false), 3000)
    }, 600)
  }

  const copyPayload = () => {
    navigator.clipboard.writeText(JSON.stringify(current.payload, null, 2))
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="rounded-2xl border border-sky-500/20 bg-[#07101f] p-6 sm:p-8 lg:p-9 shadow-2xl">
      <div className="flex flex-wrap items-center justify-between gap-4 pb-6 border-b border-white/[0.08]">
        <div>
          <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-md bg-sky-500/10 border border-sky-500/25 mb-2">
            <Sparkles className="size-3 text-sky-400" />
            <span className="font-mono text-[10px] font-bold uppercase tracking-wider text-sky-300">Live Simulator</span>
          </div>
          <h3 className="font-heading font-bold text-white text-base sm:text-lg">
            Webhook Payload Inspector &amp; Request Replayer
          </h3>
          <p className="text-zinc-400 text-xs sm:text-sm mt-1">
            Simulate incoming webhooks, inspect headers and HMAC signatures, and test request replay.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          {(['stripe', 'github', 'shopify'] as const).map((p) => (
            <button
              key={p}
              onClick={() => setSelectedEvent(p)}
              className={cn(
                'px-3.5 py-2 rounded-lg text-xs font-mono capitalize transition-all',
                selectedEvent === p
                  ? 'bg-sky-500/20 text-sky-300 border border-sky-500/40'
                  : 'bg-white/[0.03] text-zinc-400 border border-white/[0.06] hover:text-white',
              )}
            >
              {p}
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 my-6 sm:my-8">
        <div className="lg:col-span-5 rounded-xl border border-white/[0.08] bg-black/40 p-5 font-mono text-xs">
          <p className="text-[10px] text-zinc-500 uppercase tracking-widest mb-3.5 font-bold">HTTP Headers &amp; Signatures</p>
          <div className="space-y-3">
            {Object.entries(current.headers).map(([k, v]) => (
              <div key={k} className="text-zinc-300">
                <span className="text-sky-400 font-semibold">{k}:</span>{' '}
                <span className="text-zinc-400 break-all">{v}</span>
              </div>
            ))}
          </div>

          <div className="mt-5 pt-4 border-t border-white/[0.06] flex items-center justify-between text-[11px]">
            <span className="text-zinc-500">Method:</span>
            <span className="text-emerald-400 font-bold">POST</span>
          </div>
          <div className="mt-1.5 flex items-center justify-between text-[11px]">
            <span className="text-zinc-500">Endpoint:</span>
            <span className="text-zinc-300 truncate">https://hookscope-tools.vercel.app/w/demo</span>
          </div>
        </div>

        <div className="lg:col-span-7 relative rounded-xl border border-white/[0.08] bg-black/60 p-5 font-mono text-xs">
          <div className="flex items-center justify-between mb-3">
            <span className="text-[10px] text-zinc-500 uppercase tracking-widest">
              Event: <span className="text-sky-300">{current.type}</span>
            </span>
            <button
              onClick={copyPayload}
              className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-white/10 hover:bg-white/20 text-white text-[11px] transition-all"
            >
              {copied ? <Check className="size-3 text-emerald-400" /> : <Copy className="size-3" />}
              <span>{copied ? 'Copied' : 'Copy JSON'}</span>
            </button>
          </div>
          <pre className="text-sky-100 overflow-x-auto max-h-48 text-[11px]">
            {JSON.stringify(current.payload, null, 2)}
          </pre>
        </div>
      </div>

      <div className="flex flex-wrap items-center justify-between gap-3 pt-4 border-t border-white/[0.06]">
        <div className="flex items-center gap-2 text-xs font-mono">
          {replaySuccess && (
            <span className="text-emerald-400 flex items-center gap-1.5 animate-fadeIn">
              <CheckCircle2 className="size-4" /> Delivered: HTTP 200 OK (28ms)
            </span>
          )}
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleReplay}
            disabled={isReplaying}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl font-heading font-semibold text-xs text-white bg-sky-600 hover:bg-sky-500 transition-all active:scale-95 disabled:opacity-50"
          >
            <RefreshCw className={cn('size-3.5', isReplaying && 'animate-spin')} />
            <span>{isReplaying ? 'Replaying...' : 'Replay Request'}</span>
          </button>
        </div>
      </div>
    </div>
  )
}

/** ImpactCheck Interactive Sandbox: Code Diff & Breaking Change Simulator */
function ImpactCheckSimulator() {
  const [scenario, setScenario] = useState<'schema' | 'auth' | 'route'>('schema')

  const scenarios = {
    schema: {
      name: 'Database Schema Change',
      file: 'src/db/schema.ts',
      diff: [
        { type: 'remove', line: '-  role: varchar("role", { length: 32 }).default("user"),' },
        { type: 'add', line: '+  roles: varchar("roles", { length: 64 })[].notNull(),' },
      ],
      impacts: [
        { level: 'Critical', label: 'Downstream Auth Handler', text: 'JWT generator references old "role" column' },
        { level: 'High', label: 'Migration Risk', text: 'Existing users have null roles array without backfill' },
        { level: 'Medium', label: 'Client Types', text: 'UserSession interface broken in 4 API handlers' },
      ],
    },
    auth: {
      name: 'Authentication Guard Modification',
      file: 'src/middleware/auth.ts',
      diff: [
        { type: 'remove', line: '-  if (!token) return next();' },
        { type: 'add', line: '+  if (!token || !verifyHmac(token)) return res.status(401).json({ error: "Unauthorized" });' },
      ],
      impacts: [
        { level: 'High', label: 'Public Webhook Endpoints', text: 'Third-party webhooks without HMAC tokens will be rejected' },
        { level: 'Medium', label: 'Public Health Check', text: '/api/health is now protected by default' },
      ],
    },
    route: {
      name: 'API Route Contract Change',
      file: 'src/routes/api/v1/projects.ts',
      diff: [
        { type: 'remove', line: '-  GET /api/v1/projects -> { items: Project[] }' },
        { type: 'add', line: '+  GET /api/v1/projects -> { data: { projects: Project[], total: number } }' },
      ],
      impacts: [
        { level: 'Critical', label: 'Mobile Client Contract', text: 'iOS/Android client parsing will crash on root .items expectation' },
        { level: 'High', label: 'Web Dashboard Feeds', text: 'useProjectsQuery response adapter requires update' },
      ],
    },
  }

  const current = scenarios[scenario]

  return (
    <div className="rounded-2xl border border-indigo-500/20 bg-[#07101f] p-6 sm:p-8 lg:p-9 shadow-2xl">
      <div className="flex flex-wrap items-center justify-between gap-4 pb-6 border-b border-white/[0.08]">
        <div>
          <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-md bg-indigo-500/10 border border-indigo-500/25 mb-2">
            <Sparkles className="size-3 text-indigo-400" />
            <span className="font-mono text-[10px] font-bold uppercase tracking-wider text-indigo-300">Live Simulator</span>
          </div>
          <h3 className="font-heading font-bold text-white text-base sm:text-lg">
            Change Impact &amp; Breaking Change Watchlist
          </h3>
          <p className="text-zinc-400 text-xs sm:text-sm mt-1">
            Simulate code changes to inspect how ImpactCheck diagnoses affected files and downstream risks.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2.5">
          {(['schema', 'auth', 'route'] as const).map((s) => (
            <button
              key={s}
              onClick={() => setScenario(s)}
              className={cn(
                'px-3.5 py-2 rounded-lg text-xs font-mono capitalize transition-all',
                scenario === s
                  ? 'bg-indigo-500/20 text-indigo-300 border border-indigo-500/40'
                  : 'bg-white/[0.03] text-zinc-400 border border-white/[0.06] hover:text-white',
              )}
            >
              {s === 'schema' ? 'Schema Diff' : s === 'auth' ? 'Auth Guard' : 'API Route'}
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 my-6 sm:my-8">
        <div className="lg:col-span-6 rounded-xl border border-white/[0.08] bg-black/50 p-5 font-mono text-xs">
          <div className="flex items-center justify-between pb-2 mb-3 border-b border-white/[0.06]">
            <span className="text-[11px] text-zinc-400 flex items-center gap-1.5">
              <FileCode className="size-3.5 text-indigo-400" /> {current.file}
            </span>
            <span className="text-[10px] text-zinc-500 uppercase">Git Diff</span>
          </div>
          <div className="space-y-1 overflow-x-auto text-[11px]">
            {current.diff.map((d, i) => (
              <div
                key={i}
                className={cn(
                  'px-2 py-0.5 rounded font-mono',
                  d.type === 'remove' ? 'bg-rose-500/10 text-rose-300' : 'bg-emerald-500/10 text-emerald-300',
                )}
              >
                {d.line}
              </div>
            ))}
          </div>
        </div>

        <div className="lg:col-span-6 rounded-xl border border-white/[0.08] bg-[#0A1226]/60 p-4">
          <p className="text-[11px] font-mono uppercase tracking-wider text-zinc-400 mb-3 flex items-center gap-2">
            <ShieldAlert className="size-4 text-amber-400" />
            Breaking Change Watchlist
          </p>
          <div className="space-y-2.5">
            {current.impacts.map((imp, idx) => (
              <div
                key={idx}
                className="p-3 rounded-lg border border-white/[0.06] bg-black/30 flex items-start gap-3"
              >
                <span
                  className={cn(
                    'px-2 py-0.5 rounded text-[10px] font-mono font-bold uppercase shrink-0',
                    imp.level === 'Critical'
                      ? 'bg-rose-500/20 text-rose-400 border border-rose-500/30'
                      : imp.level === 'High'
                        ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30'
                        : 'bg-blue-500/20 text-blue-400 border border-blue-500/30',
                  )}
                >
                  {imp.level}
                </span>
                <div>
                  <p className="font-heading font-semibold text-white text-xs">{imp.label}</p>
                  <p className="text-zinc-400 text-[11px] leading-relaxed mt-0.5">{imp.text}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

/* ────────────────────────────────────────────────────────────────────────── */
/* 2. MAIN REDESIGNED PROJECT DETAIL COMPONENT                                */
/* ────────────────────────────────────────────────────────────────────────── */

export const ProjectDetail = () => {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const project = projects.find((p) => p.id === id)
  const safeProject = project || projects[0]

  const index = project ? projects.findIndex((p) => p.id === id) : 0
  const prevProject = projects[(index - 1 + projects.length) % projects.length]
  const nextProject = projects[(index + 1) % projects.length]

  // Image Gallery state
  const allImages = useMemo(() => [safeProject.image, ...(safeProject.gallery || [])], [safeProject])
  const [activeImageIndex, setActiveImageIndex] = useState(0)
  const [lightboxOpen, setLightboxOpen] = useState(false)
  const [copiedLink, setCopiedLink] = useState(false)

  // Feature Explorer Search state
  const [featureSearch, setFeatureSearch] = useState('')
  const filteredFeatures = useMemo(() => {
    if (!safeProject.features) return []
    return safeProject.features.filter((f) => f.toLowerCase().includes(featureSearch.toLowerCase()))
  }, [safeProject.features, featureSearch])

  // Keyboard navigation for Lightbox and Projects
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (lightboxOpen) {
        if (e.key === 'Escape') setLightboxOpen(false)
        if (e.key === 'ArrowRight') setActiveImageIndex((prev) => (prev + 1) % allImages.length)
        if (e.key === 'ArrowLeft') setActiveImageIndex((prev) => (prev - 1 + allImages.length) % allImages.length)
      } else {
        if (e.key === 'ArrowLeft' && e.altKey) navigate(`/works/${prevProject.id}`)
        if (e.key === 'ArrowRight' && e.altKey) navigate(`/works/${nextProject.id}`)
      }
    }
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [lightboxOpen, allImages.length, navigate, prevProject.id, nextProject.id])

  if (!project) return <Navigate to="/works" replace />

  const copyPageUrl = () => {
    navigator.clipboard.writeText(window.location.href)
    setCopiedLink(true)
    setTimeout(() => setCopiedLink(false), 2000)
  }

  const metaItems = [
    { icon: User, label: 'Role', value: project.role },
    { icon: Clock, label: 'Status', value: project.timeline },
    { icon: Calendar, label: 'Year', value: project.year },
    { icon: Zap, label: 'Processing', value: 'Browser-Local / Zero-Latency' },
  ]

  const overviewItems = [
    { icon: Target, label: 'The Problem', copy: project.problem, color: '#F43F5E' },
    { icon: Compass, label: 'Architectural Approach', copy: project.approach, color: '#3B82F6' },
    { icon: Trophy, label: 'Delivered Outcome', copy: project.outcome, color: '#10B981' },
  ]

  const projectJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: project.title,
    headline: project.tagline || project.description,
    description: project.longDescription,
    image: project.image,
    url: `https://usmankhatri.vercel.app/works/${project.id}`,
    dateCreated: project.year,
    applicationCategory: project.category,
    operatingSystem: 'Any (Browser-based)',
    creator: {
      '@type': 'Person',
      name: 'Usman Khatri',
      url: 'https://usmankhatri.vercel.app',
    },
    keywords: project.tech.join(', '),
  }

  return (
    <>
      <SEO
        title={`${project.title} — Case Study & Workbench`}
        description={project.tagline || project.description}
        image={project.image}
        url={`/works/${project.id}`}
        article
        jsonLd={projectJsonLd}
      />

      <main id="main-content" className="min-h-screen pt-14 sm:pt-16 pb-12 overflow-hidden bg-background">
        {/* Subtle Ambient Background */}
        <div
          aria-hidden
          className="pointer-events-none fixed inset-0 bg-[linear-gradient(to_right,rgba(147,197,253,0.03)_1px,transparent_1px),linear-gradient(to_bottom,rgba(147,197,253,0.03)_1px,transparent_1px)] bg-[size:48px_48px] z-0"
        />
        <div
          aria-hidden
          className="pointer-events-none fixed -top-32 left-1/2 -translate-x-1/2 size-[600px] rounded-full blur-[140px] opacity-20"
          style={{ background: `radial-gradient(circle, ${project.color} 0%, transparent 70%)` }}
        />

        <div className="relative z-10 max-w-6xl mx-auto px-4 sm:px-6 lg:px-10">
          {/* Top Bar: Breadcrumb + Action Controls */}
          <div className="pt-4 sm:pt-6 mb-6 flex flex-wrap items-center justify-between gap-4 border-b border-white/[0.06] pb-4">
            <div className="flex items-center gap-2 text-xs sm:text-sm font-heading">
              <Link
                to="/works"
                className="inline-flex items-center gap-1.5 text-zinc-400 hover:text-white transition-colors group"
              >
                <ArrowLeft className="size-3.5 group-hover:-translate-x-0.5 transition-transform" />
                <span>Selected Works</span>
              </Link>
              <span className="text-zinc-600">/</span>
              <span className="text-white font-semibold">{project.title}</span>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={copyPageUrl}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-white/[0.08] bg-white/[0.03] hover:bg-white/[0.07] text-zinc-300 hover:text-white text-xs font-mono transition-all"
              >
                {copiedLink ? <Check className="size-3.5 text-emerald-400" /> : <Share2 className="size-3.5" />}
                <span>{copiedLink ? 'Link Copied!' : 'Share Case Study'}</span>
              </button>

              <span className="text-zinc-600 font-mono text-xs px-1">
                {String(index + 1).padStart(2, '0')} / {String(projects.length).padStart(2, '0')}
              </span>
            </div>
          </div>

          {/* Hero Header */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: APPLE_EASE }}
            className="mb-8"
          >
            {/* Category & Status Badge */}
            <div className="flex flex-wrap items-center gap-3 mb-3">
              <span
                className="text-[11px] font-bold tracking-widest uppercase px-3 py-1 rounded-full font-heading"
                style={{
                  background: `${project.color}18`,
                  color: project.color,
                  border: `1px solid ${project.color}35`,
                }}
              >
                {project.category}
              </span>

              <span className="inline-flex items-center gap-1.5 text-xs font-mono text-emerald-400 bg-emerald-500/10 border border-emerald-500/25 px-2.5 py-0.5 rounded-full">
                <span className="size-1.5 rounded-full bg-emerald-400 animate-pulse" />
                Live in Production
              </span>
            </div>

            {/* Title */}
            <h1
              className="font-heading font-black tracking-tighter text-white mb-3"
              style={{ fontSize: 'clamp(2rem, 4.8vw, 4.2rem)', lineHeight: 1.05 }}
            >
              {project.title}
            </h1>

            {/* Prominent Tagline */}
            {project.tagline && (
              <p className="text-base sm:text-xl font-heading font-semibold text-blue-200/90 mb-4 max-w-3xl leading-snug">
                {project.tagline}
              </p>
            )}

            {/* Description */}
            <p className="text-zinc-300 text-sm sm:text-base max-w-3xl leading-relaxed mb-6">
              {project.longDescription || project.description}
            </p>

            {/* Action Bar */}
            <div className="flex flex-wrap items-center gap-3 sm:gap-4">
              {project.live && (
                <a
                  href={project.live}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 px-6 py-3 rounded-full text-xs sm:text-sm font-semibold text-white font-heading transition-all duration-300 hover:scale-[1.02] active:scale-[0.98]"
                  style={{
                    background: `linear-gradient(135deg, ${project.color} 0%, #1D4ED8 100%)`,
                    boxShadow: `0 0 28px ${project.color}45`,
                  }}
                >
                  <ExternalLink className="size-4" />
                  <span>Launch Live Tool</span>
                </a>
              )}

              {project.github && (
                <a
                  href={project.github}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 px-5 py-3 rounded-full text-xs sm:text-sm font-semibold text-zinc-300 font-heading hover:text-white transition-colors border border-white/10 hover:border-white/20 bg-white/[0.04]"
                >
                  <FiGithub className="size-4" />
                  <span>View Repository</span>
                </a>
              )}

              <a
                href="#interactive-simulator"
                className="flex items-center gap-2 px-5 py-3 rounded-full text-xs sm:text-sm font-semibold text-blue-300 font-heading hover:text-white transition-colors border border-blue-500/25 bg-blue-500/10"
              >
                <Sparkles className="size-3.5" />
                <span>Test Live Simulator</span>
              </a>
            </div>
          </motion.div>

          {/* Interactive Browser Window Stage */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: APPLE_EASE, delay: 0.1 }}
            className="mb-10 rounded-2xl sm:rounded-3xl border border-white/[0.1] bg-[#07101f] overflow-hidden shadow-[0_24px_80px_rgba(0,0,0,0.6)]"
          >
            {/* Browser Chrome Header */}
            <div className="flex items-center justify-between px-4 py-3 bg-[#0a1426] border-b border-white/[0.08]">
              {/* Traffic lights */}
              <div className="flex items-center gap-2">
                <span className="size-3 rounded-full bg-rose-500/80 inline-block" />
                <span className="size-3 rounded-full bg-amber-500/80 inline-block" />
                <span className="size-3 rounded-full bg-emerald-500/80 inline-block" />
              </div>

              {/* Simulated Address Bar */}
              <div className="flex items-center gap-2 max-w-sm sm:max-w-md w-full mx-3 px-3 py-1 rounded-lg bg-black/40 border border-white/[0.06] text-xs font-mono text-zinc-300">
                <Lock className="size-3 text-emerald-400 shrink-0" />
                <span className="truncate">{project.live}</span>
              </div>

              {/* Lightbox Trigger */}
              <button
                onClick={() => setLightboxOpen(true)}
                className="flex items-center gap-1.5 text-xs text-zinc-400 hover:text-white transition-colors font-mono"
                title="Open fullscreen lightbox"
              >
                <Maximize2 className="size-3.5" />
                <span className="hidden sm:inline">Inspect</span>
              </button>
            </div>

            {/* Active Preview Display */}
            <div
              className="relative aspect-[16/9] sm:aspect-[16/8] overflow-hidden cursor-zoom-in group"
              onClick={() => setLightboxOpen(true)}
            >
              <img
                src={allImages[activeImageIndex]}
                alt={`${project.title} screenshot ${activeImageIndex + 1}`}
                className="w-full h-full object-cover object-top transition-transform duration-700 ease-out group-hover:scale-[1.015]"
                loading="eager"
                decoding="async"
              />

              <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex items-end p-5">
                <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-black/80 border border-white/20 text-white text-xs font-mono backdrop-blur-md">
                  <Maximize2 className="size-3.5" /> Click to view full resolution
                </span>
              </div>
            </div>

            {/* Gallery Thumbnail Strip (if gallery images exist) */}
            {allImages.length > 1 && (
              <div className="flex items-center gap-2.5 p-3 sm:p-4 bg-[#050b17] border-t border-white/[0.06] overflow-x-auto">
                <span className="text-[11px] font-mono text-zinc-500 uppercase tracking-wider mr-1">Views:</span>
                {allImages.map((img, idx) => (
                  <button
                    key={img}
                    onClick={() => setActiveImageIndex(idx)}
                    className={cn(
                      'relative h-12 sm:h-16 aspect-[16/10] rounded-lg overflow-hidden border transition-all shrink-0',
                      activeImageIndex === idx
                        ? 'border-blue-400 ring-2 ring-blue-500/30'
                        : 'border-white/10 opacity-60 hover:opacity-100',
                    )}
                  >
                    <img src={img} alt={`Thumb ${idx + 1}`} className="w-full h-full object-cover" />
                  </button>
                ))}
              </div>
            )}
          </motion.div>

          {/* Metadata Cards Grid — Open spacing */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6 mb-12">
            {metaItems.map(({ icon: Icon, label, value }) => (
              <SpotlightCard key={label} className="p-5 sm:p-6 rounded-2xl">
                <Icon className="size-4.5 text-blue-400 mb-2.5" />
                <p className="text-[10px] sm:text-[11px] uppercase tracking-widest text-zinc-500 font-mono mb-1.5">{label}</p>
                <p className="font-heading font-bold text-white text-xs sm:text-sm">{value}</p>
              </SpotlightCard>
            ))}
          </div>

          <SectionDivider />

          {/* Interactive Project-Specific Sandbox Simulator */}
          <section id="interactive-simulator" className="my-10 scroll-mt-24">
            {project.id === 'migrationmap' && <MigrationMapSimulator />}
            {project.id === 'hookscope' && <HookScopeSimulator />}
            {project.id === 'impactcheck' && <ImpactCheckSimulator />}
          </section>

          <SectionDivider />

          {/* Full Feature Suite (Supporting All 13-20 Real Features) — Open Grid */}
          {project.features && project.features.length > 0 && (
            <section aria-labelledby="features-heading" className="my-10">
              <div className="flex flex-wrap items-end justify-between gap-4 mb-8">
                <div>
                  <div className="flex items-center gap-2 mb-2">
                    <span className="h-px w-6 bg-blue-500/50" />
                    <span className="font-mono text-[10px] font-bold uppercase tracking-[0.25em] text-blue-400">
                      Capability Matrix
                    </span>
                  </div>
                  <h2 id="features-heading" className="font-heading font-bold text-white text-xl sm:text-2xl">
                    Engineered Features ({project.features.length})
                  </h2>
                </div>

                {/* Real-time search filter */}
                <div className="relative w-full sm:w-72">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-3.5 text-zinc-500" />
                  <input
                    type="text"
                    placeholder="Search features (e.g. diff, export, loop)..."
                    value={featureSearch}
                    onChange={(e) => setFeatureSearch(e.target.value)}
                    className="w-full pl-9 pr-3 py-2.5 rounded-xl bg-white/[0.04] border border-white/[0.08] text-xs text-white placeholder:text-zinc-600 focus:outline-none focus:border-blue-500/50 font-mono"
                  />
                  {featureSearch && (
                    <button
                      onClick={() => setFeatureSearch('')}
                      className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-500 hover:text-white"
                    >
                      <X className="size-3" />
                    </button>
                  )}
                </div>
              </div>

              {/* Generous open gaps between feature cards */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-5 lg:gap-6">
                {filteredFeatures.map((feat, i) => (
                  <motion.div
                    key={feat}
                    initial={{ opacity: 0, y: 12 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: (i % 6) * 0.04, duration: 0.4 }}
                    className="group flex items-start gap-3.5 p-4 sm:p-5 rounded-2xl border border-white/[0.08] bg-[#07101f]/90 hover:border-blue-500/35 hover:bg-[#07101f] transition-all shadow-md"
                  >
                    <div className="size-5.5 rounded-lg bg-blue-500/10 border border-blue-500/25 flex items-center justify-center shrink-0 mt-0.5 text-blue-400 group-hover:bg-blue-500/20 transition-colors">
                      <Check className="size-3" />
                    </div>
                    <div>
                      <p className="font-heading font-medium text-zinc-200 text-xs sm:text-sm group-hover:text-white transition-colors leading-relaxed">
                        {feat}
                      </p>
                    </div>
                  </motion.div>
                ))}
              </div>

              {filteredFeatures.length === 0 && (
                <div className="text-center py-8 text-zinc-500 text-xs font-mono">
                  No features match "{featureSearch}". Clear filter to view all {project.features.length} capabilities.
                </div>
              )}
            </section>
          )}

          <SectionDivider />

          {/* System Overview: Problem → Solution → Outcome — Open Grid */}
          <section aria-labelledby="overview-heading" className="my-10">
            <div className="mb-8">
              <span className="font-mono text-[10px] font-bold uppercase tracking-[0.25em] text-blue-400 block mb-1.5">
                Deep Dive
              </span>
              <h2 id="overview-heading" className="font-heading font-bold text-white text-xl sm:text-2xl">
                Architecture &amp; Problem Solving
              </h2>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 sm:gap-8 mb-6">
              {overviewItems.map(({ icon: Icon, label, copy, color }) => (
                <SpotlightCard key={label} className="p-6 sm:p-8 rounded-2xl h-full flex flex-col gap-4">
                  <div
                    className="size-10 rounded-xl flex items-center justify-center mb-2"
                    style={{ background: `${color}15`, border: `1px solid ${color}30` }}
                  >
                    <Icon className="size-5" style={{ color }} />
                  </div>
                  <p className="text-[10px] tracking-widest uppercase font-mono text-zinc-400">{label}</p>
                  <p className="text-zinc-300 leading-relaxed text-xs sm:text-sm flex-1">{copy}</p>
                </SpotlightCard>
              ))}
            </div>
          </section>

          <SectionDivider />

          {/* Tech Stack & Ecosystem — Open spacing */}
          <section aria-labelledby="stack-heading" className="my-10">
            <div className="mb-6">
              <span className="font-mono text-[10px] font-bold uppercase tracking-[0.25em] text-blue-400 block mb-1.5">
                Technologies
              </span>
              <h2 id="stack-heading" className="font-heading font-bold text-white text-xl sm:text-2xl">
                Implementation Stack
              </h2>
            </div>

            <div className="flex flex-wrap gap-2.5 sm:gap-3">
              {project.tech.map((t, i) => (
                <TechBadge key={t} label={t} index={i} />
              ))}
            </div>
          </section>

          <SectionDivider />

          {/* Project Navigation Footer — Open grid */}
          <nav aria-label="Project switch" className="pt-8 pb-12">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 sm:gap-6">
              <button
                onClick={() => navigate(`/works/${prevProject.id}`)}
                className="group text-left p-6 sm:p-7 rounded-2xl border border-white/[0.08] bg-[#07101f]/90 hover:bg-[#07101f] hover:border-blue-500/35 transition-all flex items-center gap-5 shadow-lg"
              >
                <div className="size-11 rounded-xl bg-white/[0.04] border border-white/[0.08] flex items-center justify-center shrink-0 group-hover:-translate-x-1 transition-transform">
                  <ArrowLeft className="size-4 text-blue-400" />
                </div>
                <div className="min-w-0">
                  <span className="text-[10px] font-mono uppercase tracking-widest text-zinc-500 block mb-1.5">
                    Previous Project
                  </span>
                  <p className="font-heading font-bold text-white text-base truncate">{prevProject.title}</p>
                  <p className="text-zinc-500 text-xs truncate mt-0.5">{prevProject.category}</p>
                </div>
              </button>

              <button
                onClick={() => navigate(`/works/${nextProject.id}`)}
                className="group text-right p-5 rounded-2xl border border-white/[0.08] bg-[#07101f]/80 hover:bg-[#07101f] hover:border-blue-500/30 transition-all flex items-center justify-end gap-4"
              >
                <div className="min-w-0">
                  <span className="text-[10px] font-mono uppercase tracking-widest text-zinc-500 block mb-1">
                    Next Project
                  </span>
                  <p className="font-heading font-bold text-white text-base truncate">{nextProject.title}</p>
                  <p className="text-zinc-500 text-xs truncate mt-0.5">{nextProject.category}</p>
                </div>
                <div className="size-10 rounded-xl bg-white/[0.04] border border-white/[0.08] flex items-center justify-center shrink-0 group-hover:translate-x-1 transition-transform">
                  <ArrowRight className="size-4 text-blue-400" />
                </div>
              </button>
            </div>
          </nav>
        </div>
      </main>

      {/* Fullscreen Interactive Lightbox Modal */}
      <AnimatePresence>
        {lightboxOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/95 backdrop-blur-xl p-4 sm:p-8"
            onClick={() => setLightboxOpen(false)}
          >
            {/* Close Button */}
            <button
              onClick={() => setLightboxOpen(false)}
              className="absolute top-5 right-5 size-10 rounded-full bg-white/10 hover:bg-white/20 text-white flex items-center justify-center transition-all z-20"
              aria-label="Close image modal"
            >
              <X className="size-5" />
            </button>

            {/* Prev Image Button */}
            {allImages.length > 1 && (
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  setActiveImageIndex((prev) => (prev - 1 + allImages.length) % allImages.length)
                }}
                className="absolute left-4 sm:left-8 size-12 rounded-full bg-white/10 hover:bg-white/20 text-white flex items-center justify-center transition-all z-20"
                aria-label="Previous image"
              >
                <ChevronLeft className="size-6" />
              </button>
            )}

            {/* Next Image Button */}
            {allImages.length > 1 && (
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  setActiveImageIndex((prev) => (prev + 1) % allImages.length)
                }}
                className="absolute right-4 sm:right-8 size-12 rounded-full bg-white/10 hover:bg-white/20 text-white flex items-center justify-center transition-all z-20"
                aria-label="Next image"
              >
                <ChevronRight className="size-6" />
              </button>
            )}

            {/* Image Container */}
            <div
              className="relative max-w-6xl max-h-[85vh] w-full flex flex-col items-center"
              onClick={(e) => e.stopPropagation()}
            >
              <img
                src={allImages[activeImageIndex]}
                alt={`${project.title} view ${activeImageIndex + 1}`}
                className="max-h-[80vh] w-auto max-w-full rounded-xl object-contain shadow-2xl border border-white/10"
              />
              <p className="mt-3 text-xs font-mono text-zinc-400">
                {project.title} · Image {activeImageIndex + 1} of {allImages.length} (Press Esc to close)
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  )
}
